services:
  timescale:
    container_name: auth-storage-timescale
    image: timescale/timescaledb-ha:pg18.1-ts2.24.0
    command: >
      postgres -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10
    environment:
      POSTGRES_USER: "anhle"
      POSTGRES_PASSWORD: "anhle"
      POSTGRES_DB: "auth_storage"
      TZ: "UTC"
    ports:
      - "54320:5432"
    volumes:
      - timescale_data:/home/postgres/pgdata/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anhle -d auth_storage"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      auth-storage-network:
        aliases:
          - timescale

  redis:
    image: redis:7-alpine
    container_name: auth-storage-redis
    command: ["redis-server", "--requirepass", "anhle"]
    environment:
      - TZ=UTC
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "anhle", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      auth-storage-network:
        aliases:
          - redis

  migrate:
    image: anhle3532/auth-storage-migrate:dev-latest
    environment:
      - DB_URL=postgres://anhle:anhle@timescale:5432/auth_storage?sslmode=disable
    command: ["-path", "/migrations/sql", "up"]
    depends_on:
      timescale:
        condition: service_healthy
    networks:
      - auth-storage-network

  spicedb:
    image: authzed/spicedb:latest
    container_name: auth-storage-spicedb
    command: ["serve", "--datastore-engine=memory"]
    ports:
      - "50051:50051"
    environment:
      - SPICE_DB_DEBUG_LOG_LEVEL=debug
      - SPICEDB_GRPC_PRESHARED_KEY=Wc/Q0tGYtxkF0ygKRSG1NiiTHkKVbld4autfkglRBU4=
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      auth-storage-network:
        aliases:
          - spicedb

  spicedb-init:
    image: authzed/zed:latest
    container_name: auth-storage-spicedb-init
    depends_on:
      spicedb:
        condition: service_healthy
    volumes:
      - ../../internal/data/db/migrations/spicedb/schema.zed:/app/schema.zed:ro
    command: schema write /app/schema.zed --endpoint=spicedb:50051 --token=Wc/Q0tGYtxkF0ygKRSG1NiiTHkKVbld4autfkglRBU4= --insecure
    networks:
      - auth-storage-network

  hashicorp:
    image: hashicorp/vault:latest
    container_name: auth-storage-hashicorp
    ports:
      - "8200:8200"
    command: ["vault", "server", "-config=/vault/config/vault-config.hcl"]
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_UI: "true"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - ../../vault-config.hcl:/vault/config/vault-config.hcl
    networks:
      auth-storage-network:
        aliases:
          - hashicorp

  api:
    container_name: auth-storage-api
    image: anhle3532/auth-storage:dev-latest
    env_file:
      - ./dev.env
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      timescale:
        condition: service_healthy
      redis:
        condition: service_healthy
      spicedb:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      spicedb-init:
        condition: service_completed_successfully
    networks:
      - auth-storage-network

networks:
  auth-storage-network:
    driver: bridge

volumes:
  timescale_data:
  redis_data:
  vault_data:
