server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    enable: true
    driver: pgx
    source: postgres://anhle:anhle@localhost:5432/auth_storage?sslmode=disable
  redis:
    enable: true
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  spicedb:
    enable: true
    endpoint: localhost:50051
    token: Wc/Q0tGYtxkF0ygKRSG1NiiTHkKVbld4autfkglRBU4=
    insecure: true
