server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  kid: 484a19bafc6671c073a97b6bd31f069e
data:
  database:
    enable: true
    driver: pgx
    source: postgres://anhle:anhle@localhost:54320/auth_storage?sslmode=disable
  redis:
    enable: true
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: "anhle"
    db: 0
  spicedb:
    enable: true
    endpoint: localhost:50051
    token: Wc/Q0tGYtxkF0ygKRSG1NiiTHkKVbld4autfkglRBU4=
    insecure: true
