// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"server/internal/biz"
	"server/internal/conf"
	"server/internal/data"
	"server/internal/server"
	"server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	authRepo := data.NewUserRepo(dataData, logger)
	privatePEM, err := data.NewPrivatePEM(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publicPEM, err := data.NewPublicPEM(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	spiceClient, err := data.NewSpiceClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authUseCase, err := biz.NewAuthUseCase(authRepo, privatePEM, publicPEM, spiceClient, confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(authUseCase)
	m2MAuthRepo := data.NewM2MAuthRepo(dataData, logger)
	m2MAuthUseCase, err := biz.NewM2MAuthUseCase(m2MAuthRepo, privatePEM, confServer, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	m2MAuthService := service.NewM2MAuthService(m2MAuthUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger, authService, m2MAuthService)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, authService, m2MAuthService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
